version: '2'

services:

  server:
    image: bsandusky/poll-server:0.1
    container_name: server
    environment:
      - MONGO_URI=mongodb://mongodb/polls
    links:
      - database
    ports:
      - "8000:8000"

  database:
    image: mongo
    container_name: mongodb
    command: --smallfiles
